### ISSUE TITLE
Atom consistently quits responding when opening a specific file

### ISSUE THREAD

**Issue by Kelendria** [atom/atom.io#108]
I have a file that is consistently crashing Atom. I've followed the flight manual, reset to factory defaults and even uninstalled, rebooted and reinstalled.  The crash log just says it couldn't start the dumper.

I've been working on this file in Atom for close to a year now but last night it just started crashing Atom for no apparent reason.  It's less than a 400k file and I've edited much larger without issue. Other editors don't seem to have a problem with the file.

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

This repository is for the atom.io website not for the Atom editor. Please open a new issue in [atom/atom](https://github.com/atom/atom/issues) for the problem you are having and make sure to completely fill out the provided issue template.

**Comment by Kelendria** [comment]
I thought I might be in the wrong place. Thanks!
