### ISSUE TITLE
[Website] "Other platforms" link still redirects to FAQ on atom.io

### ISSUE THREAD

**Issue by thedaniel** [atom/atom.io#11]
_From @mnquintana on January 21, 2015 15:16_

Now that Atom is available for all platforms, I think it would be better UX to instead actually show the releases for the other platforms when you click "Other platforms" from the home page. Right now, it just redirects to the FAQ question, which just states that builds are available for all of these platforms, but doesn't actually direct you to download them (instead it seems to suggest that you have to compile it yourself if you want to use it).

_Copied from original issue: atom/apm#266_

**Comment by thedaniel** [comment]
_From @pwaring on February 17, 2015 11:32_

I've noticed this as well. It might also be worth making clear on any downloads page that only 64-bit builds are supported for Linux - it's a bit frustrating to follow all the links and then find out that 'Linux support' actually means '64-bit Linux for x86' (e.g. it won't run on a Raspberry Pi).

**Comment by AgentME** [comment]
This issue appears to have been fixed.

**Comment by izuzak** [comment]
Thanks, @AgentME -- yeah, I think that was fixed recently.
