### ISSUE TITLE
Atom.io downloads are not working until Amazon S3 outage is resolved

### ISSUE THREAD

**Issue by skull-squadron** [atom/atom.io#112]
https://atom-installer.github.com/v1.14.4/atom-mac.zip?s=1488270996&ext=.zip on https://atom.io/ 

```
Error 503 Connection timed out

Connection timed out

Guru Mediation:

Details: cache-ams4124-AMS 1488309373 3483990621

Varnish cache server
```

Also, this presents in the app with the following error:

```
There was an error checking for updates.

Update download failed. The server sent an invalid response. Try again later.
```

**Comment by skull-squadron** [comment]
~~**Temporary workaround:** Download from [github directly](https://github.com/atom/atom/releases).~~ Github also uses S3 US-EAST-1, so they're down too.

**Comment by BinaryMuse** [comment]
This is due to [an S3 outage](https://status.aws.amazon.com/):

> Update at 10:33 AM PST: We're continuing to work to remediate the availability issues for Amazon S3 in US-EAST-1. AWS services and customer applications depending on S3 will continue to experience high error rates as we are actively working to remediate the errors in Amazon S3.

I'll leave this open for now (cc @lee-dohm) so others can find it until things are resolved.

**Comment by skull-squadron** [comment]
Ah thanks.

**Comment by danielesegato** [comment]
Do you have any temporary mirror / alternatives for downloading installers?

**Comment by rsese** [comment]
> Do you have any temporary mirror / alternatives for downloading installers?

I don't believe so, looks like there's an issue with this request though /cc https://github.com/atom/apm/issues/488.

**Comment by BinaryMuse** [comment]
This should be resolved; only writes to S3 are still broken.

**Comment by rsese** [comment]
> > Do you have any temporary mirror / alternatives for downloading installers?

> I don't believe so, looks like there's an issue with this request though /cc atom/apm#488.

Sorry just realized you were asking about installers not packages @danielesegato :bow:

**Comment by skull-squadron** [comment]
All good now. AWS status page [was also out-of-date](https://news.ycombinator.com/item?id=13756922) because it depended upon S3 US-EAST-1 az. (Circular-dependency, whoops.)
