### ISSUE TITLE
Screenshot renders incorrectly on iPad

### ISSUE THREAD

**Issue by jasonrudolph** [atom/atom.io#123]
Following the screenshot updates for https://github.com/atom/atom.io/issues/120, the screenshot seems to render correctly on various phone and desktop browsers that I've tested, but it's rendering incorrectly on the iPad. The following screenshot is from the current version of Chrome on an iPad running iOS 10:

![img_0527](https://user-images.githubusercontent.com/2988/26927562-6811a2ac-4c20-11e7-8707-900b725f1e54.PNG)

@simurai: Would you mind taking a look at this issue?

**Comment by jsejcksn** [comment]
I'm seeing the same problem on Chrome 59.0.3071.86 on Windows 10.

I notice that in the CSS, the class `screenshot-main` applied to that span has a WxH ratio matching the image, but the `background-size` property does not, and is causing it to be compressed along the y-axis.

**Comment by simurai** [comment]
@jsejcksn Yes, right, the `background-size` didn't get updated. Should now be fixed: https://atom.io

**Comment by marlazinger200** [comment]
1
