### ISSUE TITLE
Link to GH repo from webpage

### ISSUE THREAD

**Issue by RyanZim** [atom/atom.io#124]
I find it frustrating that there's no direct link between https://atom.io and https://github.com/atom/atom

Not sure where the link should be; possible locations:

- Top bar
- Fork me on Github corner banner
- Keep in touch section
- Bottom bar

**Comment by BinaryMuse** [comment]
There's a small textual link under "Open source" on the bottom of the home page, but I agree there could be a more prominent and permanently accessible location for this.

/cc @simurai for feels/💭 s

**Comment by simurai** [comment]
How about

- a bit harder to miss "Fork on GitHub" button
- link to Atom org in "Keep in touch"

![screen shot 2017-06-15 at 9 19 23 pm](https://user-images.githubusercontent.com/378023/27181358-416268b0-5212-11e7-9f26-32d7bc68c82d.png)

**Comment by RyanZim** [comment]
@simurai Perfect! :tada: :octocat:
