### ISSUE TITLE
Atom for GitHub

### ISSUE THREAD

**Issue by balandinodidonato** [atom/atom.io#127]
## To reproduce
- Follow step one for setting up Atom with GitHub

## Expected
- The page [https://github.atom.io/login](https://github.atom.io/login) opens correctly

## Actual
- The page does not hope. Error message: _Oops! There was a problem._

**Comment by winstliu** [comment]
@balandinodidonato what browser are you using?

**Comment by balandinodidonato** [comment]
@50Wliu Chrome

**Comment by Aitchy** [comment]
Just had the same with a new Windows 7 setup of GitHub Desktop & Atom.  I'm trying to clone my wiki repository and get told in Atom to visit the above link and generate an authentication token.

When I try this (IE11) iget the same error message.

Link is https://github.atom.io/auth/failure?message=csrf_detected&strategy=github_package

**Comment by JiElPe-Fr38** [comment]
Dear All,

I have the same problem with Firefox 58.02 on Windows 7 SP1.
**Finally it works**... _but only if I am not already connected to my gitHub repository on a Firefox tab_.

**Comment by rsese** [comment]
Can you reproduce in another browser like the latest release Chrome @JiElPe-Fr38?  

> Finally it works... but only if I am not already connected to my gitHub repository on a Firefox tab.

Just to clarify, do you mean that you can only avoid the error if you're already logged into your GitHub account?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom.io/issues/127#issuecomment-365447384. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
