### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by jyn514** [atom/atom.io#131]
As discussed [here](https://github.com/atom/node-oniguruma/issues/68), there's a weird link on this page of the site: https://atom.github.io/node-oniguruma/. I'd like to submit a pull request, but I can't seem to find the right repository.

**Comment by lee-dohm** [comment]
The content on that page is auto-generated from the atom/node-oniguruma README at https://github.com/atom/node-oniguruma. You can submit a PR on that repo :+1:
