### ISSUE TITLE
Can't authorize GitHub for Atom

### ISSUE THREAD

**Issue by tautf** [atom/atom.io#133]
Hey,

when i Access https://github.atom.io/login and try to authroize Atom im recieving Oops! Something went wrong. somebody has an idea?

Running latest Atom Version on Win 7 Enterprise. Browser is IE.

Thank you

**Comment by jasonrudolph** [comment]
Hi @FlorianTaut: Are you still able to reproduce this issue? If so, can you please reply with a specific date and time (including time zone) when you observed this issue? That info may help us get a better understanding of the problem.

**Comment by tautf** [comment]
@jasonrudolph Hey, no im not.

I don't know where the issue was but when i tried to set a different browser as my Default it worked...
