### ISSUE TITLE
Website doesn't load CSS

### ISSUE THREAD

**Issue by sandeepskak** [atom/atom.io#135]
Check the attached screenshots for details.
![atom](https://user-images.githubusercontent.com/8362676/30362840-67c716ea-987b-11e7-885e-192dafe386c1.PNG)

**Comment by winstliu** [comment]
Looks like a temporary internet connectivity issue due to the `ERR_CONNECTION_TIMED_OUT` error.  If it still happens tomorrow please comment here and I'll reopen the issue.

**Comment by anion155** [comment]
Same happened to me today...
![screenshot from 2017-12-17 20-46-33](https://user-images.githubusercontent.com/4786672/34081179-6a1edc1c-e36b-11e7-9024-74a002ec8457.png)
