### ISSUE TITLE
https://atom.io/packages/toggler should have a install button

### ISSUE THREAD

**Issue by ElvarP** [atom/atom.io#140]
Next to the repo button there should be a install button. It should be high contraxt so people can immediately see it.

I would make a pull request but the documentation doesn't point me to the website.

![image](https://user-images.githubusercontent.com/11872349/31792978-6038872a-b50d-11e7-96fe-26e386c9554b.png)

You would only need to add this line of css.

```
.package-meta ul li:first-child
 {
    background-color: #00ffa3 ;
}
```

The html is pretty straightforward.

Not sure if the Atom team supports web urls like skype does, but that is something to think about implementing. Would be an easy way to get the userbase to start installing more packages.

**Comment by winstliu** [comment]
We're slowly working on getting the necessary URI handler support integrated in Atom.  When all of that is done there will most likely be an "Install" button present on package pages.  Thanks for the feedback though!
