### ISSUE TITLE
Consider enabling compression for text-type responses

### ISSUE THREAD

**Issue by Ingramz** [atom/atom.io#141]
As it turned out during the investigation in https://github.com/atom/settings-view/pull/1014, atom.io currently does not leverage any sort of content compression for its text type responses. It is possible that by enabling compression, especially slower connections can benefit from reduced loading times, thus improving website loading times overall and also speeding up API responses like the search functionality when installing a new package.

checkgzipcompression.com shows that [a](https://checkgzipcompression.com/?url=https%3A%2F%2Fatom.io%2F) [number](https://checkgzipcompression.com/?url=https%3A%2F%2Fatom.io%2Fapi%2Fpackages%2Fsearch%3Fq%3Dgithub) [of](https://checkgzipcompression.com/?url=https%3A%2F%2Fatom.io%2Freleases) [responses](https://checkgzipcompression.com/?url=https%3A%2F%2Fatom.io%2Fpackages) could be compressed 3 to 4 times smaller compared to the original size.

cc @nathansobo @jasonrudolph @iolsen

**Comment by jasonrudolph** [comment]
Thanks for this suggestion. We've rolled out an update to atom.io to support compression for text-type responses.

Example: https://checkgzipcompression.com/?url=https%3A%2F%2Fatom.io%2F

If you observe any problems related to this change, please let us know. :bow:

**Comment by Ingramz** [comment]
I am seeing a healthy speed boost of at least 50-100ms per request across the board. Thanks!
