### ISSUE TITLE
It wont issue an authentication token for my account

### ISSUE THREAD

**Issue by SpillChek2** [atom/atom.io#149]
Tried to authenticate my account with github, and keeps on giving an error message, I have the repo under my organization account called Creative WebMatrix Solutions I did grant it, but its not working, please can some one assist me with this matter?

**Comment by jasonrudolph** [comment]
Thanks for getting in touch. I'll try to help.

> Tried to authenticate my account with github, and keeps on giving an error message

What is the error message that you're seeing when you attempt to authenticate? Can you share a screenshot?

> I have the repo under my organization account called Creative WebMatrix Solutions I did grant it, but its not working...

Can you please provide a link to the repository?

Can you tell us more about what you're trying to accomplish? For example, are you trying to publish an Atom package?

**Comment by SpillChek2** [comment]
Oh hi @jasonrudolph, no Thank you for reaching out!
It's all good, I was having a hard time getting started, its all under control now!
