### ISSUE TITLE
Its Not Responsive in all devices  

### ISSUE THREAD

**Issue by mukesh4601** [atom/atom.io#150]
![screenshot from 2018-01-16 12-06-27](https://user-images.githubusercontent.com/28723602/34975036-da2531ee-fab5-11e7-9394-e72ff4f366de.png)
Its not Responsive yet

**Comment by rsese** [comment]
Thanks for the feedback!  I believe this was done a month or two after you opened this issue, maybe along with the home page redesign I think.

![responsive-site](https://github-slack.s3.amazonaws.com/monosnap/Atom_2018-12-05_20-37-19.png)
