### ISSUE TITLE
Add an Install button on a package page

### ISSUE THREAD

**Issue by haacked** [atom/atom.io#153]
Atom has support for installing packages via a URL handler.

`atom://settings-view/show-package?package=PACKAGENAME`

That support has been out for a while now. It is probably a good time to add an install button on atom.io when listing a package.

Today, the page for a package will list multiple ways to install it. For most people, it'd be simpler to just give them a link to click to launch Atom and install the package.

**Comment by BinaryMuse** [comment]
Also relevant: https://github.com/atom/atom/issues/16532

**Comment by simurai** [comment]
There is already a "View in Atom" button:

![screen shot 2018-03-27 at 2 46 39 pm](https://user-images.githubusercontent.com/378023/37949092-1b08a2be-31ce-11e8-9063-b0de35c52941.png)

But it's probably easy to miss. Maybe we can move it out of the row with the other buttons and also add a color. So it will look more like "this is the most important thing on the page".

**Comment by haacked** [comment]
I just picked a package at random and don't see that button.

![image](https://user-images.githubusercontent.com/19977/37978888-f8fb19ae-319b-11e8-8fbc-b80a35692711.png)

**Comment by Arcanemagus** [comment]
That button definitely isn't on the live site at least...

**Comment by BinaryMuse** [comment]
It's staff shipped https://github.com/github/atom.io/pull/1199

**Comment by BinaryMuse** [comment]
(Where "staff" means something totally different than usual 😅)

**Comment by haacked** [comment]
I do think "View in Atom" is a bit unclear. When I see that, I think "Why would I want to view it in Atom?" It's not immediately clear that's how I would install it.

If someone is visiting a package page, chances are the task they want to accomplish is to install the package. That's why I think the page should make that prominent. It helps people accomplish the task at hand.

**Comment by simurai** [comment]
> @BinaryMuse (Where "staff" means something totally different than usual 😅)

Ohh.. you mean it's hard-coded to certain usernames? Ooops, sorry for leaking that. :speak_no_evil:

> @Haacked I do think "View in Atom" is a bit unclear.

Yeah, I agree. Here a mockup with an "Install" button. When clicked, it would open Atom and show the package:

![screen shot 2018-03-28 at 12 19 09 pm](https://user-images.githubusercontent.com/378023/38007061-944ca7f6-3282-11e8-9244-e7e7c08fdcd8.png)

Is that too misleading or confusing? People might not realise that they have to click "Install" a 2nd time in the settings. Other options:

- Atom's settings could show a dialog: "Install package?" [Cancel] [Install]
- The package page could have an "Install section" where there is more room to explain. "Open in Atom where you can install this package". Plus show the `apm install` command, that a lot of packages seem to add to their README.

**Comment by haacked** [comment]
> Is that too misleading or confusing?

I don't think so. It's a good first step. There's always room to iterate on the experience.

One way to make it more clear is to use the ellipses convention on the Install button to indicate that it's taking you somewhere to install the package.

`[Install...]`

Also, what happens if you click that link and Atom isn't installed? It may make sense to use the approach Jason Long did here: https://github.com/github/github/pull/82198

The short of it is clicking shows a pop-up that describes what should be happening and what to do if nothing happens. The click also initiates the URL protocol handler at the same time.

**Comment by simurai** [comment]
> The short of it is clicking shows a pop-up that describes what should be happening and what to do if nothing happens.

💯 That's nice way of keeping it simple, plus have an explanation and fallback for edge cases. 😍

**Comment by jasonrudolph** [comment]
You can now install packages directly from atom.io! 😄

https://twitter.com/AtomEditor/status/1063528390991450112
