### ISSUE TITLE
ATOM CRASH

### ISSUE THREAD

**Issue by Fehintibaby** [atom/atom.io#155]
ATOM keeps crashing and asks me to reload, or keep open. What can I do?

**Comment by Arcanemagus** [comment]
Thanks very much for the report!

Would you mind reopening this issue in the https://github.com/atom/atom repository, including completely filling out the template? We use multiple repositories to keep the work items tied to the code they apply to. This helps the maintainers spend more time working directly on Atom and less time triaging issues.

Thanks for meeting us halfway :+1:
