### ISSUE TITLE
Several items on a grid are a bit off

### ISSUE THREAD

**Issue by Powell-v2** [atom/atom.io#157]
Would look nicer if straightened out 😀 

<img width="1075" alt="screen shot 2018-05-06 at 12 44 06" src="https://user-images.githubusercontent.com/25308326/39672517-add71892-512b-11e8-9018-f1bb6fdb8f6f.png">
<img width="1071" alt="screen shot 2018-05-06 at 12 44 17" src="https://user-images.githubusercontent.com/25308326/39672518-adf045d8-512b-11e8-95d2-4cb5fd5c3e13.png">

**Comment by simurai** [comment]
> Several items on a grid are a bit off

👍 Let's use CSS grid. And single column as fallback.
