### ISSUE TITLE
Text gets cut off due to width constraints.

### ISSUE THREAD

**Issue by Subh0m0y** [atom/atom.io#158]
![Text cut off](https://user-images.githubusercontent.com/11086749/39699667-cb5637f8-5217-11e8-842f-791952f8d1ec.png)

Notice how the right columns have their extreme right edges cut off the text weirdly. I suppose it's a rendering problem?

Chrome - Version 66.0.3359.139 (Official Build) (64-bit)

**Comment by jasonrudolph** [comment]
Thanks for the report, @Subh0m0y. :bow:

@simurai: When you have a moment, can you look into this?

**Comment by Arcanemagus** [comment]
@pe.lallemant in #atom:

> This is caused due to `grid-gap: 100px 66px` on the `.features`

**Comment by simurai** [comment]
It seems using the `fr` unit like `grid-template-columns: 1fr 1fr`, automatically takes the `grid-gap` into account. Should be fixed now.

@Subh0m0y Thanks for noticing. 🙇
