### ISSUE TITLE
Cannot Receive Token for Atom

### ISSUE THREAD

**Issue by edwardnorth3** [atom/atom.io#159]
When trying to authenticate my github account in atom, it takes me to the github, but it says, "Oops! There was a problem."

**Comment by rsese** [comment]
Thanks for the report - which browser are you using?  Also, can you reproduce the problem in multiple browsers?

x-ref: https://github.com/atom/atom.io/issues/127

**Comment by edwardnorth3** [comment]
It takes me to internet explorer when I click on it. I ended up having to type the link into chrome to get it to work right, bit it seems like I should be able to just right click on the link and pick where to go. I know it's only a minor inconvenience, but it is nonetheless bothersome.

**Comment by rsese** [comment]
Thanks @edwardnorth3 - what version of Internet Explorer is that and what version of Windows are you running?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom.io/issues/159#issuecomment-404682409. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
