### ISSUE TITLE
Screenshot on atom.io homepage shows old theme

### ISSUE THREAD

**Issue by thedaniel** [atom/atom.io#16]
_From @russlescai on May 31, 2015 22:30_

I know this is minor in the scheme of things, but I noticed the homepage for https://atom.io still has the Atom Dark theme, not the One Dark UI theme as the screenshot.

_Copied from original issue: atom/atom#7043_

**Comment by thedaniel** [comment]
_From @mnquintana on June 4, 2015 1:16_

This might not get updated till 1.0 lands, but I'm not really sure.

**Comment by thedaniel** [comment]
_From @russlescai on June 4, 2015 10:52_

no biggy more an observation. :)

**Comment by russlescai** [comment]
Thanks @thedaniel - looks like it has since been updated so this issue can now be closed.

:+1:
