### ISSUE TITLE
changing login credentials

### ISSUE THREAD

**Issue by iraizo** [atom/atom.io#161]
Today i changed my github name and now i cant push updates since the login credentials are outdated any way to update them?

**Comment by rsese** [comment]
Thanks for reaching out - just to clarify, when you say "can't push updates", do you mean that you're having trouble pushing commits using the [GitHub package](https://github.com/atom/github/)?

**Comment by iraizo** [comment]
yes

**Comment by rsese** [comment]
This issue was moved to atom/github#1621

**Comment by ClementGre** [comment]
I find a solution : I unlog from GitHub in Atom, then i add the remote in command line and I can push After that, I re-login me with a token, on Atom, and it's work ! 
![image](https://user-images.githubusercontent.com/51322714/81598014-e996c000-93c6-11ea-9e5e-e9f5594f6e39.png)
