### ISSUE TITLE
I need a token.

### ISSUE THREAD

**Issue by cldavis3burnsmcd** [atom/atom.io#162]
Atom/GitHub will not give me token

**Comment by rsese** [comment]
Thanks for the report!  Can you share more details?  E.g. can you share steps to reproduce the behavior you're seeing?  Are you getting an error of some kind?   If you can share a screenshot of what you see, that might help as well.

Lastly, please share what version of Atom you're running (`atom -v`) and what operating system.

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom.io/issues/162#issuecomment-408559587. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
