### ISSUE TITLE
Documentation on code spans in config schema

### ISSUE THREAD

**Issue by zypA13510** [atom/atom.io#167]
Although I can infer from the markdown syntax that code spans are quoted by backticks `` ` ``, but the documentation [here](https://atom.io/docs/api/v1.30.0/Config#title-and-description) really confused me.

Why do we have this
> `code spans` - `\`code spans\`\`

instead of this?
`code spans` - `` `code spans` ``

Btw, I can't seem to find the source code of documentation anywhere.

**Comment by Aerijo** [comment]
@zypA13510 I believe that's 'just' the markdown generator making a mistake. The source for that is [here](https://github.com/atom/atom/blob/5479e1c78989b9a5a79bed9780b7b58b1461afa1/src/config.js#L314), and they are clearly trying to put in escaped back ticks like you suggest. It's still an issue, just a different reason.

**Comment by zypA13510** [comment]
@Aerijo No, I think maybe they made a mistake here?

> ``` `code spans` - `\`code spans\`` ```

`code spans` - `\`code spans\``

> ``` `code spans` - `` `code spans` `` ```

`code spans` - `` `code spans` ``

You mentioned that the documentation is generated from the source? So if I make a PR fixing that and the doc will be fixed too?

**Comment by Aerijo** [comment]
I meant that the backslashes seem to be to escape the `` ` ``, but you're right that that's not how GFM markdown works.

I believe a PR would fix it, but I don't know how to run the generator to check. It could be they are using one that doesn't support arbitrary backticks starting code snippets.

**Comment by Arcanemagus** [comment]
The source is parsed with [joanna](https://github.com/atom/joanna) and that metadata is turned into an intermediate format with [tello](https://github.com/atom/tello) that then gets turned into the final documentation with [atomdoc](https://github.com/atom/atomdoc).

It's... complicated to debug, however I made it quite a bit simpler when I added the [`--generate-api-docs`](https://github.com/atom/atom/pull/17057) command to the build script.
