### ISSUE TITLE
Can't get a token

### ISSUE THREAD

**Issue by greenisagoodcolor** [atom/atom.io#169]
![atom](https://user-images.githubusercontent.com/7354163/45784715-9f276500-bc1e-11e8-808c-812bfa0f5b86.png)

I am trying to get a token to authenticate my atom, except it won't grant it to me. I am logged in github when I request. I am using archlinux/kde

**Comment by rsese** [comment]
Thanks for the report - which browser are you using? Also, can you reproduce the problem in multiple browsers and with all browser extensions disabled?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom.io/issues/169#issuecomment-429567013. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by ecotechie** [comment]
I can confirm. I have tried it on Firefox logged in/out to GitHub and same with Chrome. Both on Linux. Is there a way to manually create the token? Like from the [New Personal Access Token](https://github.com/settings/tokens/new) page? If so what settings are the default ones?
