### ISSUE TITLE
Link to "build from source" on Linux points to GitHub instead of flightmanual.

### ISSUE THREAD

**Issue by HonkingGoose** [atom/atom.io#178]
**Problem:**

The link to Linux "build from source" from atom.io takes 2 steps to get to the right resource.

**Steps to reproduce:**

1. Use Firefox browser on Linux.
1. Go to the main atom.io page at https://atom.io/
1. Go to the section "build from source".
1. The "build from source" link points to: https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md while that page on GitHub links to: https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#platform-linux

**Suggested improvement:**
Link to the flight-manual section directly instead.

**Discussion:**
Is there a good reason why this resource links to GitHub instead of to the flight-manual?

**Comment by jasonrudolph** [comment]
:wave: @HonkingGoose: This is fixed now. Thanks for bringing this to our attention. 

![Screen Shot 2019-04-23 at 12 53 51 PM](https://user-images.githubusercontent.com/2988/56600594-0c411580-65c7-11e9-843a-8c88e2c454ba.png)

**Comment by HonkingGoose** [comment]
Thanks for fixing it. :tada:
