### ISSUE TITLE
Link to "Packages & Themes" is incorrect

### ISSUE THREAD

**Issue by harryscholes** [atom/atom.io#179]
Currently: `https://atom.io/packages.atom`. Presumably it should be `https://atom.io/packages`.

**Comment by winstliu** [comment]
Hmm, do you mean this link?
![atom-io-packages-and-themes](https://user-images.githubusercontent.com/2766036/54716286-c60e1780-4b2b-11e9-80ee-072ed0493675.png)

**Comment by harryscholes** [comment]
Yep

**Comment by winstliu** [comment]
Thanks! I believe that link is actually correct, as it's supposed to link to an [RSS feed](https://en.wikipedia.org/wiki/RSS).
