### ISSUE TITLE
Redirect error

### ISSUE THREAD

**Issue by harshattray** [atom/atom.io#182]
- Clicking on the Packages & Themes link on the footer redirects to a `view-source` kind of page.
![Screenshot 2019-05-31 at 7 54 53 AM](https://user-images.githubusercontent.com/3311805/58677545-13073900-837a-11e9-92f5-dfd065f09eaf.png)

**Comment by winstliu** [comment]
Yeah, this is intentional - note that it says "RSS Feed" to the left of it. This page is meant for consumption by RSS readers. If you want to see the user-facing pages, they're in the header.
