### ISSUE TITLE
language-rust-bundled package link outdated

### ISSUE THREAD

**Issue by Aerijo** [atom/atom.io#183]
The `Repo` link for [language-rust-bundled](https://atom.io/packages/language-rust-bundled) goes to the [old deprecated repo](https://github.com/atom/language-rust), not the [`atom/packages/language-rust-bundled`](https://github.com/atom/atom/tree/master/packages/language-rust-bundled) repo

**Comment by lee-dohm** [comment]
Unarchived, updated the README with the standard header (taken from atom/go-to-line), re-archived.

Thanks!
