### ISSUE TITLE
Atom rtags error

### ISSUE THREAD

**Issue by xueyang94** [atom/atom.io#184]
Everytime I edit my .cpp file, a message pops up: Rtags executor process restarted, please try again. I have Rtags package installed and up to date. The .cpp file compiles and runs fine. Is there a way to stop the message from showing up? Thanks.

**Comment by rsese** [comment]
Thanks for reaching out!  And sorry for any confusion, as mentioned in the [README](https://github.com/atom/atom.io#atomio-site-feedback), this repository is for feedback about the Atom.io website and the apm package API, but it's not for questions about using Atom.

For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
