### ISSUE TITLE
searching packages with api returns "Application Error"

### ISSUE THREAD

**Issue by UziTech** [atom/atom.io#203]
Searching for packages in Atom is broken.

Settings-View trys to search atom.io with the query:
https://atom.io/api/packages/search?q={query}&filter=package

but it always responds with {"message":"Application error"}

Searching for the package on https://atom.io/packages and clicking the <kbd>Install</kbd> button still works

![image](https://user-images.githubusercontent.com/97994/88295706-64cbfa80-ccc3-11ea-841f-3eaa7f22387d.png)

**Comment by UziTech** [comment]
Looks like the same issue is happening again. https://github.com/atom/atom/issues/21131

**Comment by UziTech** [comment]
Same thing is happening again https://github.com/atom/atom/issues/21155

**Comment by yecril71pl** [comment]
[Something has gone wrong (500)](https://atom.io/packages/search?q=run)

**Comment by ryanolsonx** [comment]
Are you guys gonna fix this?!

**Comment by ddaza** [comment]
I get the feeling that the prioritization of Atom has been put in the Extinguish backlog.

**Comment by chriswhite199** [comment]
@darangi - Can you re-open this issue, seeing as it's still ongoing?

**Comment by chriswhite199** [comment]
You can, if you know the package name, still install a package via apm.

A google search with the `site:` keyword can help here, for example:

`site:atom.io/packages file icons` will have this result: https://atom.io/packages/file-icons, which can then be installed:

```
apm install file-icons
```

**Comment by UziTech** [comment]
You can also search for the package on https://atom.io/packages and click the <kbd>Install</kbd> button

![image](https://user-images.githubusercontent.com/97994/88295706-64cbfa80-ccc3-11ea-841f-3eaa7f22387d.png)

**Comment by yecril71pl** [comment]
I do not know the package name.

**Comment by chriswhite199** [comment]
@yecril71pl - So use google search by keywords related to the package you want, for example say you wanted anything docker related: 

* https://www.google.com/search?q=site:atom.io/packages%20docker

(I'm not advocating for this to be the 'fix', just a work around until the site maintainers can look into the cause)

**Comment by chriswhite199** [comment]
Well it's all working again, so someone fixed something

**Comment by ivan006** [comment]
its happening again
