### ISSUE TITLE
Windows Installer Download Link Broken

### ISSUE THREAD

**Issue by Lionole** [atom/atom.io#204]
When I click on Download (Windows Version 1.50.0) from the Atom.io Website, I get this error.

![image](https://user-images.githubusercontent.com/22672414/90994921-4ab65e00-e588-11ea-8f8e-87489a576245.png)

**Comment by sadick254** [comment]
All windows download links are working. Please try downloading from the [releases](https://github.com/atom/atom/releases/tag/v1.50.0)
