### ISSUE TITLE
Run Atom natively on a Mac M1 ?

### ISSUE THREAD

**Issue by freebrowser1** [atom/atom.io#210]
## Summary

Is there a way to build Atom on Mac M1 ?

## Motivation

Because Electron is already available natively and can be built using Homebrew which also runs natively (i.e. without Rosetta). I just built it on a Mac Mini M1.

**Comment by sadick254** [comment]
Hey @freebrowser1 . We have ongoing work to enable Atom to run on Mac M1. We have an open PR https://github.com/atom/atom/pull/21777. You can follow updates on that PR. I will close this for now. Thanks for reporting this.

**Comment by Ulisses1478** [comment]
Now that is merged its possible to build myself?

> Hey @freebrowser1 . We have ongoing work to enable Atom to run on Mac M1. We have an open PR [atom/atom#21777](https://github.com/atom/atom/pull/21777). You can follow updates on that PR. I will close this for now. Thanks for reporting this.

**Comment by freebrowser1** [comment]
Did not work. I installed Electron from homebrew and it put the binary into /Applications, but when running Atom the Activity Monitor still tells 'Intel'.
