### ISSUE TITLE
Download link broken for Windows x64 installer

### ISSUE THREAD

**Issue by tristanbob** [atom/atom.io#218]
### Description

Can't download Windows installer from main website.

### Steps to Reproduce

1. Attempt to download Windows x64 binary by clicking on the button "Download" (which points to "https://atom.io/download/windows_x64")
 
**Expected behavior:**

File download begins.

**Actual behavior:**

Browser is redirected to:
https://atom-installer.github.com/v1.57.0/AtomSetup-x64.exe?s=1620674356&ext=.exe

`<Error>
<Code>BlobNotFound</Code>
<Message>The specified blob does not exist. RequestId:0dc9b32b-701e-0073-7bf1-6a7af6000000 Time:2021-06-27T01:10:45.3166845Z</Message>
</Error>
`

**Reproduces how often:**

100%

**Comment by darangi** [comment]
Hello @tristanbob thanks for reporting. This has been fixed 🎉
