### ISSUE TITLE
atom.io down

### ISSUE THREAD

**Issue by jay-tux** [atom/atom.io#229]
### Prerequisites
(unrelated)
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

[atom.io/packages] seems to be down. Not only the frontend, but also the package manager seems to be having a lot of trouble installing basically any package. The main site is also extremely unresponsive/slow.

### Steps to Reproduce

1. go to [atom.io] and watch it load a very long long long time, ending with a server error (if at all)
2. check internet connection (okay, I can ping google) - try pinging atom (no results whatsoever)
3. cry

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

Seemingly all the time (the website was very very slow before, now it doesn't react at all).

### Versions

not applicable

**Comment by darangi** [comment]
Can you verify you are still experiencing this?

**Comment by jay-tux** [comment]
Both sites are back online. 
`apm install` seems to be working again as well. 
@darangi can you give me any information on the causes?
