### ISSUE TITLE
Unable to register package

### ISSUE THREAD

**Issue by chuank** [atom/atom.io#24]
I'm having no success in trying to publish my package.

apm login works, but every `apm publish minor` keeps returning:
![image](https://cloud.githubusercontent.com/assets/1781911/9377594/de975dfa-475d-11e5-8a33-80a55ab51d7f.png)

I got prompted for my Github credentials once, which I provided an access token for (I'm using 2FA), but it never seems to work.

Running git from my command line works fine when managing my other github repos.

I'm happy to completely wipe my atom account clean and try again.

Entire details of the problem are described in the atom discussion forum:
https://discuss.atom.io/t/publishing-packages-doesnt-prompt-for-github-credentials-fails/19490

**Comment by thedaniel** [comment]
@chuank Try logging out and in on the atom.io website and then trying to publish again from the command line. Recently GitHub expired a bunch of idle credentials so it's possible that refreshing them in this way will fix your API issues.

**Comment by james2doyle** [comment]
![screen shot 2015-08-21 at 1 05 51 pm](https://cloud.githubusercontent.com/assets/1425304/9417954/61c7d360-4805-11e5-958f-cdc538c0fb61.png)

I tried logging out and logging in, then relogging into apm, and I still get this issue.

**Comment by thedaniel** [comment]
@james2doyle I took a look at the logs and it seems that something specific to your package might be causing this. I'll update this thread as I learn more.

**Comment by james2doyle** [comment]
ok great thanks

**Comment by thedaniel** [comment]
@james2doyle 

The way the API database indexes package.json contents means your giant 147KB package.json file is raising errors. This could be plauslibly fixed on the backend, but in the meantime, you should find a way to shrink it down. There's not really a good reason for a package.json file to be that big anyway.

It looks like you maybe copied the package.json out of an atom.io API result or a raw search result for another package and modified it, which adds all sorts of unnecessary metadata. Try taking out these keys - the last one, `_atomModuleCache` seems to be responsible for 99% of your file size and is unnecessary.

```
_id: "jquery-snippets@1.0.0",
_shasum: "8655c80dede427eaac93576f347d34acfb617dd5",
_resolved: "file:..\d-115718-6324-2xml0s\package.tgz",
_from: "..\d-115718-6324-2xml0s\package.tgz",
_atomModuleCache: {...}
```

**Comment by james2doyle** [comment]
@thedaniel ok thanks, I dont use Atom but I accepted a PR with these changes. Once removed it looked like it published!

**Comment by thedaniel** [comment]
Hurray!

**Comment by chuank** [comment]
Thanks @thedaniel logging out and back into atom.io worked, and the package is now published.

I have an older, stub package that I was using to troubleshoot this issue, and I'd like to unpublish and remove it ([particle-offline-compile](https://atom.io/packages/particle-offline-compile)). I believe I deleted the repo once before, which resulted in a broken link between apm and github. I've tried `apm unpublish` but I keep getting this error:

![image](https://cloud.githubusercontent.com/assets/1781911/9458805/940553d2-4b36-11e5-8752-4a5338dff482.png)

I don't mind wiping this away from the atom packages db; it's just a stub. I can't find a way to do that, though. Can it only be done by yourself / someone at atom.io?

**Comment by izuzak** [comment]
@chuank Done -- it has been removed.

**Comment by chuank** [comment]
thanks @izuzak!

i did something stupid while waiting for a response – there's another `particle-offline-compileold` stub that now shows up as another orphaned package – please delete that too. thanks again

**Comment by izuzak** [comment]
Deleted that one as well, @chuank

**Comment by chuank** [comment]
thanks!
