### ISSUE TITLE
Stable 500 error code

### ISSUE THREAD

**Issue by whutao** [atom/atom.io#240]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Atom repeatedly produces 500 errors on the web. It is also not possible to search/install packages using desktop. Seems that there may be a problem on the server side.

### Steps to Reproduce

1. Go to [Atom.io](https://atom.io) or try search for a package in the desktop version.

**Expected behavior:**

Everything works.

**Actual behavior:**

The 500 error stub or the error message in the terminal.

**Reproduces how often:**

Always...

### Versions

I'm using macOS Monterey 12.6, Atom 1.60.0

**Comment by AdrianAmenKoSoroka** [comment]
Same Happening on my side Running Windows 10 64Bit
also apm doesn't work as mentioned

**Comment by isaackielma** [comment]
Not sure if related at all. But if I go to atom.io, when I open regular browser I get 500 error. On private mode or incognito mode website opened without 500 error.


<img width="1436" alt="Screenshot 2022-10-25 at 10 17 04" src="https://user-images.githubusercontent.com/84313603/197783549-a9012f8b-1ab6-4ba1-a81b-dfa9e4e90b64.png">
<img width="1433" alt="Screenshot 2022-10-25 at 10 17 30" src="https://user-images.githubusercontent.com/84313603/197783560-989e6964-1336-4664-af43-d2392954cea0.png">

**Comment by ekungurov** [comment]
500 status code, is something wrong with the site?

**Comment by vatofichor** [comment]
Still an ongoing issue.. Haven't heard of anything on this yet.

**Comment by whutao** [comment]
Guys... Atom will no longer be supported soon :) Seems that they gradually shut down their backend.
