### ISSUE TITLE
Please make links for v0.186.0 or previous documentation redirect to https://atom.io/docs/latest

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom.io#25]
We are receiving reports of numerous people referring to old documentation because when they click "go to latest" from really old links, it takes them to v0.186.0, i.e. pre-atom/docs documentation. It would be better if things like https://atom.io/docs/v0.186.0/your-first-package was redirected to https://atom.io/docs/latest and have to find the "your first package" stuff than to be stuck looking at outdated and ever-increasingly incorrect documentation.

**Comment by fedorov** [comment]
To clarify, the problem (at least with this particular page) is that it is not possible to access the latest (or it does not exist). Clicking on the "go to latest" redirects to the same page.

**Comment by thedaniel** [comment]
Thanks for the report, we'll look into it - I like the solution of just using redirects to abandon pre-Flight Manual docs.

**Comment by thedaniel** [comment]
Docs 186 and earlier now redirect to the latest landing page (flight manual or API). Thanks for the idea, and I'll remove the old doc versions from the db / various dropdowns soon.

**Comment by lee-dohm** [comment]
Thanks @thedaniel, this will be a big help!

**Comment by fedorov** [comment]
I am still missing the response why your-first-package page has not been upgraded to the latest documentation. Sounds like an important page to me.

**Comment by lee-dohm** [comment]
@fedorov check the latest documentation, there are two whole sections on writing packages with examples:

https://atom.io/docs/latest/hacking-atom-package-word-count
https://atom.io/docs/latest/hacking-atom-package-modifying-text

**Comment by fedorov** [comment]
yes, I am aware of those, I guess it is just reorganization decision. Thanks!
