### ISSUE TITLE
"undefined" in docblock doesn't appear in API docs

### ISSUE THREAD

**Issue by ssorallen** [atom/atom.io#27]
If "undefined" appears in a docblock, the word does not make it to the generated documentation. One example is for `PackageManager::getLoadedPackage`.

Source:
![screen shot 2015-08-24 at 1 55 52 pm](https://cloud.githubusercontent.com/assets/29612/9452324/6bbeea92-4a68-11e5-8390-fe66977ca9bc.png)

Generated doc:
![screen shot 2015-08-24 at 1 55 22 pm](https://cloud.githubusercontent.com/assets/29612/9452329/6fe34cbc-4a68-11e5-8a9c-320207b3237a.png)

**Comment by ssorallen** [comment]
This appears to be fixed:
<img width="307" alt="screen shot 2018-05-24 at 12 31 35 am" src="https://user-images.githubusercontent.com/29612/40438129-db20fe28-5ee9-11e8-98cd-61dbef2d69c2.png">

**Comment by Arcanemagus** [comment]
This was fixed in https://github.com/atom/atomdoc/pull/16, thanks for noticing and closing your issue!
