### ISSUE TITLE
Document Windows 10 support

### ISSUE THREAD

**Issue by CosmicWebServices** [atom/atom.io#29]
Works great on Windows 10 can you make the website say that

**Comment by adamralph** [comment]
Agreed. First thing I noticed on the site was "For Windows 7 & 8"

**Comment by CosmicWebServices** [comment]
yes

**Comment by thedaniel** [comment]
Thanks - I updated the copy to say "Windows 7 or later"

**Comment by CosmicWebServices** [comment]
thx
