### ISSUE TITLE
Stop using flash in 'copy token' button in atom.io/account

### ISSUE THREAD

**Issue by asantos3** [atom/atom.io#31]
Just using an old version of ZeroClipboard, right?

**Comment by mnquintana** [comment]
Does ZeroClipboard not use Flash anymore? I haven't found any evidence of that from looking at their release notes.

**Comment by asantos3** [comment]
A while ago github stopped using flash for their copy buttons https://redd.it/3if6hu

I thought it was a new version of ZeroClipboard or something. Just use the clipboard API while falling back to ZeroClipboard then.

**Comment by winstliu** [comment]
I have Flash disabled by default and the token copied fine.  Seems like this has been fixed.
