### ISSUE TITLE
Recently Updated grid broken

### ISSUE THREAD

**Issue by OmgImAlexis** [atom/atom.io#32]
The 2nd to last grid item for "Recently Updated" doesn't line up correctly for some reason.

![screen shot 2015-09-27 at 2 19 15 pm](https://cloud.githubusercontent.com/assets/6525926/10121267/e2b389d0-6522-11e5-829b-8f8dde63e7f1.png)

**Comment by thomasjo** [comment]
I'm unable to reproduce this. Are you still able to? If so, what browser (including version) and OS are you using?

**Comment by OmgImAlexis** [comment]
Chrome 45.0.2454.99 (Official Build) (64-bit) on OSX 10.10.5 (14F27). I can't reproduce it anymore I'm assuming it was a bug that was specific to the items from the screenshot.

**Comment by izuzak** [comment]
I can reproduce this reliably -- it's a problem with packages which have lots of keywords, it seems. See:

https://atom.io/users/izuzak

<img width="799" alt="screen shot 2015-09-27 at 10 17 42" src="https://cloud.githubusercontent.com/assets/38924/10121860/0655a4c6-6501-11e5-943f-3c1483434d8b.png">

cc @thedaniel @simurai

**Comment by OmgImAlexis** [comment]
@thedaniel was this fixed?

**Comment by thedaniel** [comment]
Just deploying a fix for this now - this issue was auto-closed by the PR in the private repo for atom.io.

**Comment by OmgImAlexis** [comment]
Okay, just making sure it wasn't accidently closed because of a commit. :+1:
