### ISSUE TITLE
can't install any package 

### ISSUE THREAD

**Issue by izuzak** [atom/atom.io#36]
_From @MohamedTita on October 27, 2015 0:23_

Unable to download https://www.atom.io/api/packages/color-picker/versions/2.0.13/tarball: DEPTH_ZERO_SELF_SIGNED_CERT

O.S Fedora 22

_Copied from original issue: atom/atom#9298_

**Comment by izuzak** [comment]
Are you still seeing this problem? Are you behind a proxy of some kind? This works fine for me:

```
$ apm install color-picker
Installing color-picker to /Users/izuzak/.atom/packages ✓
```

Also cc @thedaniel

**Comment by MohamedTita** [comment]
apm install color-picker worked !!
and no i'am not behind any proxy

**Comment by izuzak** [comment]
@MohamedTita Thanks. Can you open a new issue on https://github.com/atom/settings-view then and provide a screenshot of the error and clear instructions which reproduce the problem for you? Please also include Atom and OS version as you did before.

**Comment by MohamedTita** [comment]
ok thank you ..
