### ISSUE TITLE
[Suggestion] Make changelogs mandatory for packages

### ISSUE THREAD

**Issue by Stanzilla** [atom/atom.io#38]
It's an annoying and confusing experience to only encounter a changelog on some apps and see it missing on others, I would love to see having this as a requirement to being able to host packages on atom.io.

**Comment by thomasjo** [comment]
There's no sensible way to enforce this in a proper manner; people will just end up with empty changelog files or fill them with garbage. Encouraging people to manage changelogs is a good thing, but enforcing it is without a doubt a bad move.

There has been discussions about surfacing the changelog during package updates, in https://github.com/atom/settings-view/issues/282, which you might want to subscribe to. But ultimately this is about educating developers and encouraging a better workflow, not force them.
