### ISSUE TITLE
Code of conduct in the footer points to v1.2.0

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom.io#45]
The atom/atom repository and Discuss point to v1.3.0.

**Comment by jasonrudolph** [comment]
I think this is resolved. The code of conduct in the footer now points to the master branch:

<img width="897" alt="Screen Shot 2019-06-13 at 4 43 36 PM" src="https://user-images.githubusercontent.com/2988/59466106-770a1280-8dfa-11e9-9068-8d7e74eec95c.png">
