### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by Shreyas94** [atom/atom.io#46]
In this [page](https://atom.io/docs/v1.3.2/hacking-atom-the-init-file) the link to the Atom API in the first paragraph of the content leads to [this link](https://atom.io/docs/api/v1.3.2/Atom). The correct link would be [this](https://atom.io/docs/api/v1.3.2/AtomEnvironment). 
 * Correct link : https://atom.io/docs/api/v1.3.2/AtomEnvironment
 * The mistake : https://atom.io/docs/api/v1.3.2/Atom

**Comment by veniversum** [comment]
Link is still broken on [latest doc version](https://atom.io/docs/latest/hacking-atom-the-init-file).
