### ISSUE TITLE
Application error, package already registered

### ISSUE THREAD

**Issue by Adezandee** [atom/atom.io#47]
Hi,
I've been trying to setup semantic-release workflow for my plugin today with [last-release-apm](https://github.com/Adezandee/last-release-apm) adapter and I didn't got the configuration right on the first time and now my package seems pretty badly messed up : see here https://atom.io/api/packages/fast-eslint

Could you clean the DB a bit from v1.1.3 please ?
Thx !

**Comment by Adezandee** [comment]
Got a question about apm publish,
When you use `$ apm publish -t sometag` the backend registry fetch this the package.json from git to determine the version to release ?
That's kinda annoying because semantic-release is based on the fact that no version is commited into the repository (because npm publish creates a tarball from whatever is the current state of the filesystem at the time the command is run).

Thanks

**Comment by thedaniel** [comment]
That's correct, all apm releases are tied to git tags in public github repositories, and the tarballs are created by pulling them from the github archive API.

**Comment by thedaniel** [comment]
Can you clarify a little bit how your package is messed up? I'm not sure what you are expecting to see, so I'm not sure what kind of cleanup you are asking for.

**Comment by Adezandee** [comment]
Hi @thedaniel 
Thanks for your response, I got unstuck by running `apm unpublish` witch deleted the entire repository and started from scratch. The side effect was that I lost my download count :cry: . But my semantic-release flow with CircleCI works now great ! See [this guide I just written](https://github.com/Adezandee/last-release-apm/blob/master/HOW.md).
