### ISSUE TITLE
Improve visibility of RSS feed?

### ISSUE THREAD

**Issue by Gruntfuggly** [atom/atom.io#48]
Hi there

I raised an issue on the atom discussion boards about the lack of an RSS feed for package releases and updates. Somebody kindly pointed out that there is one, but they had to search for it to find it.

Maybe a link to it could be added to the "Keep in Touch" section at the bottom of the page?

Now I've found the RSS feed, my original issue isn't quite so important - I was wondering about displaying dates/times on the packages page. It might still be quite useful though.

Cheers,
Nige

**Comment by thedaniel** [comment]
Thanks for the feedback - I agree that this is worth adding.

**Comment by zeke** [comment]
@Gruntfuggly what is the RSS URL?

**Comment by lee-dohm** [comment]
@zeke https://atom.io/packages.atom

**Comment by zeke** [comment]
`atom`, ha! Thanks @lee-dohm.
