### ISSUE TITLE
Windows Installer misses .exe extension if downloaded with IE11

### ISSUE THREAD

**Issue by mgarciaisaia** [atom/atom.io#51]
I haven't tested other IE versions, but if I download Atom (from https://atom.io/download/windows ) using IE11, the downloaded file is called "AtomSetup" (with no extension), and can't be double-clicked.

If I use Firefox on the same computer, I get "AtomSetup.exe", and all works OK.

**Comment by lee-dohm** [comment]
In the other issue I just linked, it seems that this is only reproducible on Windows 7. Is that what you have installed @mgarciaisaia? I thought you said you installed Windows 8.1?

**Comment by mgarciaisaia** [comment]
Just to be sure I'm not drunk:

![ie11-win81x86](https://cloud.githubusercontent.com/assets/1190974/12600604/cf0a88a0-c479-11e5-9adf-7038ed4f01b7.gif)

It's the VM Microsoft offers for testing IE11/Win81 over VirtualBox at [this site](https://dev.windows.com/en-us/microsoft-edge/tools/vms/mac/).


This is what you get:

![ie11-win81x86-try-open](https://cloud.githubusercontent.com/assets/1190974/12600690/6018497c-c47a-11e5-8992-1a8eaaa3c995.gif)


I have to test why the Firefox installer, for naming one, downloads OK.

**Comment by mgarciaisaia** [comment]
OK - I don't get _why_, but I get the cause.

Both AtomSetup.exe and Firefox Installer (the one you get from http://getfirefox.com) miss their .exe extension when you add query string parameters to the URL.

I mean, clicking the Download Windows button in atom.io gets me to https://atom-installer.github.com/v1.4.1/AtomSetup.exe?s=143124325 (some numbers, possibly a timestamp). That URL gets me a `AtomSetup` file without extension. The same URL **without** the `?s=14...` thing works OK.

And something similar happens with Firefox Setup: getfirefox.com takes me to a `Firefox Something.exe` download, and it works OK. But if I try the same URL with `?s=....` or any other query string, it doesn't work.

If I click "other platforms" on atom.io to go to the GitHub Releases page, there the download of the AtomSetup.exe works both with and without query string parameters.

I don't know why, but that's what I could find out ^_^

**Comment by 50Wliu** [comment]
Interesting how this works on Windows 10 but fails on 7/8.  Does Windows 10 contain an IE update that 7 and 8 didn't receive?

**Comment by 50Wliu** [comment]
Also, I noticed that your dev tools say "Edge" while mine says "11" (in addition to looking a lot different).

**Comment by mgarciaisaia** [comment]
We could try reaching someone at Microsoft to check why this happens, but in the meantime, I'd go for linking to the `exe` without the `?s=...` query string, or linking to the Github Releases file - that would make sense anyway, right?

**Comment by paulcbetts** [comment]
I mean, even if you find out why, what are you gonna do about it - Microsoft is definitely not going to send down a patch to fix this (they are actually legally bound to _only_ send security updates for old software that isn't optional), so you gotta just live with the status quo

**Comment by damieng** [comment]
Two possible solutions here:

- Add ?s=.exe to the URL
- Set the content-disposition on the download

It would appear the bug is that on Windows 7 version of IE in the absence of a content-disposition they scan the url for the file extension and don't account for query parameters.

**Comment by mgarciaisaia** [comment]
I've confirmed adding a `.exe` at the end of the string - even if it's a query parameter like `?s=124124.exe` - works. Good catch @damieng :)

**Comment by arirubinstein** [comment]
Confirmed this on vanilla windows server 2012 R2 standard / IE 11.0.9600.18283

**Comment by BinaryMuse** [comment]
This should be fixed with recent changes to Atom.io's download mechanism. Please feel free to reopen this issue if you continue to experience trouble.

**Comment by mgarciaisaia** [comment]
I can confirm this got fixed - tested on the same IE11/Win8.1 environment from which I reported.

Thanks for that!

**Comment by BinaryMuse** [comment]
We had to revert some of the changes we made that inadvertently fixed this issue, inadvertently re-breaking it :)

**Comment by BinaryMuse** [comment]
Fixed for reals this time :)
