### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by Shreyas94** [atom/atom.io#53]
[This link](https://atom.io/docs/v1.4.1/ch00/_customizing_keybindings) which ought to lead to the page in the documentation on mapping keys to commands leads to the Atom Flight Manual Page. There seems to be some sort of redirect.

**Comment by lee-dohm** [comment]
Would you mind reopening this on the https://github.com/atom/docs repository? That's where this bug comes from.

Thanks for reporting the issue!
