### ISSUE TITLE
[Website-Security] Please provide a way to check downloaded contents e.g. SHA hashes

### ISSUE THREAD

**Issue by ottlinger** [atom/atom.io#57]
### Description

Is it possible to provide SHA hashes to verify downloads from https://atom.io?
This would allow a checking/verification of the downloaded artifact.
### Steps to Reproduce
1. Visit https://atom.io
2. Select a download

**Expected behavior:** [What you expected to happen]

I'd love to confirm that the downloaded contents is the same as the one that was published. 
Other big organizations such as Apache Software Foundation provide signatures, while other just print md5-hashes. 
These could be integrated into the webpage or provided upon download as

```
atom-amd64.deb
atom-amd64.deb.sha256
```

**Actual behavior:** [What actually happened]

You just download a versionless "potentially" insecure file that is installed with root privileges.
### Versions

1.5.1 .... 1.27.0 still has the same problem.

**Comment by ottlinger** [comment]
@50Wliu any chance that a way to verify the downloaded contents can be added?

**Comment by lee-dohm** [comment]
Thanks for reaching out.

We don't publish the hashes of our download packages for the following reasons:

1. All of our files are downloadable via HTTPS connections using certificates that can be verified by any browser
1. If you don't trust the code on https://atom.io to serve the correct binaries, then you can always go directly to https://github.com/atom/atom/releases to get the binaries
1. If you assume, rightly, that any website can be hacked, there have been multiple cases where hacked websites provided rogue binaries and updated the hashes to match the rogue binaries, so hashes don't provide any additional security

Essentially, hashes only show you that you downloaded what you clicked on, not that what you clicked on can be trusted. HTTPS is a much better system (provided you check that the security certificate is for the organization you expect) for ensuring that you download something from the person or organization you expect to.
