### ISSUE TITLE
Atom API tutorial for Workspace >> Opening needs to be correct

### ISSUE THREAD

**Issue by KSXGitHub** [atom/atom.io#58]
Go to [this link](https://atom.io/docs/api/v1.5.3/Workspace#instance-open), see `options.split`. It tells me to use `"left"`, `"right"` `"top"`, `"bottom"` but atom actually uses `"left"`, `"right"`, `"up"`, `"down"`.

**Comment by lee-dohm** [comment]
This is already fixed in the [code from where the documentation is generated](https://github.com/atom/atom/blob/master/src/workspace.coffee#L397). Thanks for reporting!
