### ISSUE TITLE
Please show atom latest version on the homepage

### ISSUE THREAD

**Issue by breaddevil** [atom/atom.io#59]
With no auto update it is difficult to see if I am running an older version. Even the downloaded file name has no version mention.

Currently I have to go to https://github.com/atom/atom/releases/latest to figure that out, which was not obvious, it beeing named "Other platforms".

Maybe I am missing something?

**Comment by winstliu** [comment]
It's present now.
![atom-io-latest-release](https://user-images.githubusercontent.com/2766036/43233432-22fadf5a-9033-11e8-9a04-085db90eed0a.png)
