### ISSUE TITLE
Coffee code method declarations wrong

### ISSUE THREAD

**Issue by voylinux** [atom/atom.io#60]
Please note that Coffee code is being wrongly rendered and method definitions as changing -> to -&gt; special character line in [https://atom.io/docs/v1.6.0/hacking-atom-tools-of-the-trade](https://atom.io/docs/v1.6.0/hacking-atom-tools-of-the-trade)

This may be confusing for people not so used to read Coffee code.

`
MyPackageView = require './my-package-view'

module.exports =
  myPackageView: null

  activate: (state) -&gt;
    @myPackageView = new MyPackageView(state.myPackageViewState)

  deactivate: -&gt;
    @myPackageView.destroy()

  serialize: -&gt;
    myPackageViewState: @myPackageView.serialize()
`

**Comment by thomasjo** [comment]
Thanks for the report! :bow: 

I'm closing this however, since this has already been reported in https://github.com/atom/docs/issues/173.
