### ISSUE TITLE
v1.5.4 or higher document sanitized html charactors

### ISSUE THREAD

**Issue by Arakaki** [atom/atom.io#61]
[v1.5.3](https://atom.io/docs/v1.5.3/using-atom-snippets)
``` html
<html>
  <head>
    <title></title>
  </head>
  <body>

  </body>
</html>
```

[v1.5.4](https://atom.io/docs/v1.5.4/using-atom-snippets)
``` html
&lt;html&gt;
  &lt;head&gt;
    &lt;title&gt;&lt;/title&gt;
  &lt;/head&gt;
  &lt;body&gt;

  &lt;/body&gt;
&lt;/html&gt;
```

**Comment by 50Wliu** [comment]
Assuming this has been fixed with the conversion from Atlas to Nanoc (see atom/flight-manual.atom.io#173 for more details).
