### ISSUE TITLE
Include yaourt command

### ISSUE THREAD

**Issue by denysvitali** [atom/atom.io#63]
Since installing from repository is always the best choice, why don't you guys include a simple "yaourt -S atom-editor" in the homepage? I always get confused with the fact that atom is / isn't in the official repository of Arch or in the user repository (AUR). Plus, the package name "atom" in AUR is already taken, so "atom-editor" is the right one.
Those little things may create confusion, whilst a simple `yaourt -S atom-editor` textbox would be great

**Comment by lee-dohm** [comment]
The official distributions of Atom are available for download from the home page or https://github.com/atom/atom/releases. When Atom is officially available in package Linux package managers, we'll update the home page to indicate that with instructions on how to install from there. You may want to subscribe to https://github.com/atom/atom/issues/2956 for updates on that effort.

**Comment by denysvitali** [comment]
Thanks for clarifying!
