### ISSUE TITLE
Flight manual documentation incomplete

### ISSUE THREAD

**Issue by reesjones** [atom/atom.io#67]
"The Flow" section is incomplete - currently just a bulleted list with a TODO at the end.

Location of incomplete documentation: 
[http://flight-manual.atom.io/hacking-atom/sections/package-word-count/#the-flow](http://flight-manual.atom.io/hacking-atom/sections/package-word-count/#the-flow

**Edit**: The "Making our tests work" section is also incomplete.

Link: [http://flight-manual.atom.io/hacking-atom/sections/package-word-count/#making-our-tests-work](http://flight-manual.atom.io/hacking-atom/sections/package-word-count/#making-our-tests-work)

**Comment by 50Wliu** [comment]
Please reopen this on the [atom/flight-manual.atom.io](https://github.com/atom/flight-manual.atom.io) repository instead.  Thanks!
