### ISSUE TITLE
License file not recognized by package website

### ISSUE THREAD

**Issue by idleberg** [atom/atom.io#68]
I've already created an [issue](https://github.com/atom/package-generator/issues/41) for `package-generator`, but this is probably the more appropriate place for this issue:

> The package generator creates a Markdown file as license (`LICENSE.md`), but that incompatible to the Atom package website, which expects a `LICENSE` file without extension. If a Markdown file is for the license, the License-button on the website will remain greyed out.

Ideally, the website would work with `LICENSE`, `LICENSE.md` and maybe `LICENSE.txt`.

**Comment by 50Wliu** [comment]
All three should work, but I believe there's currently a problem with the backend where it's not recognizing any license files.

/cc @lee-dohm

**Comment by lee-dohm** [comment]
We know about the problem and I have a manual process that can go through and clean things up as a workaround for now. It's not a 100% thing, kind of intermittent. The website supports all three versions and even will do its best to detect if you only specify the license by name in the `package.json`.

**Comment by danielbayley** [comment]
+1. I noticed this recently too.

**Comment by mattstratton** [comment]
+1 This is occurring on https://atom.io/packages/linter-cookstyle as well. I have tried renaming `LICENSE` to `LICENSE.md` and that didn't seem to matter.

**Comment by lee-dohm** [comment]
As I [stated above](https://github.com/atom/atom.io/issues/68#issuecomment-218235579), this isn't an issue with the name of the file, it is an intermittent website issue.

**Comment by ce3a** [comment]
Same issues here https://atom.io/packages/language-dts

**Comment by lee-dohm** [comment]
Ran the batch process to update all the packages. Everyone's license should be there now.

**Comment by JustParsa** [comment]
hi there! My package likewise seems to be having this issue https://atom.io/packages/atom-ember-component

**Comment by JustParsa** [comment]
@lee-dohm ^

**Comment by pixxx** [comment]
Can't this intermittent website issue get fixed?

**Comment by felipecrp** [comment]
Same problem here. Package.json with license, github repository with license, but atom package page is missing license. Check https://atom.io/packages/highlight-cursor-line

**Comment by felipecrp** [comment]
Problem solved today. I think atom package site have a delay to update license.

**Comment by jasonrudolph** [comment]
> I believe there's currently a problem with the backend where it's not recognizing any license files.

We've deployed some updates that should resolve the problem. As you publish a new package (or a new version of an existing package), [atom.io](https://atom.io) should correctly display your package's license. We've also backfilled the license info on [atom.io](https://atom.io) for all previously published packages. If you continue to observe this problem, please let us know. :bow:
