### ISSUE TITLE
apm publish gives Application Error

### ISSUE THREAD

**Issue by thedaniel** [atom/atom.io#7]
_From @noseglid on May 12, 2015 19:34_

Not sure if this is where this issue should go. Please direct me to the correct forum otherwise.

I get this:

```
$ apm publish -t v0.32.0
Publishing build@v0.32.0 ✗
Creating new version failed: Application error
```

I've debugged a little, and it appears I get `500 Internal Server Error` from the API. So likely something is off with whatever `apm` communicates with.

_Copied from original issue: atom/apm#364_

**Comment by thedaniel** [comment]
_From @lee-dohm on May 13, 2015 0:30_

Have you done an `apm login` to make sure that it has your credential?

**Comment by thedaniel** [comment]
_From @noseglid on May 13, 2015 6:6_

Yes I have. This is the 32nd release of this package I am doing from the exact same setup.

**Comment by thedaniel** [comment]
_From @noseglid on May 13, 2015 18:41_

(I don't really think it's a problem with `apm`. The request for publishing looks fine from what I can tell. It's likely to be something with the service running at `atom.io`)

**Comment by thedaniel** [comment]
Yeah any time atom.io 500s it's a concern. I'll look into it when I have a moment.

**Comment by thedaniel** [comment]
_From @cs150bf on May 14, 2015 0:11_

I'm also seeing "Application Error". Tagging and pushing went okay. The new release (`v0.1.2`) shows up just fine on [the releases page of my git repo](https://github.com/cs150bf/ever-notedown/releases), but not on the [atom.io package page](https://atom.io/packages/ever-notedown) as it still says `v0.1.1`.

**Comment by thedaniel** [comment]
_From @noseglid on May 14, 2015 8:43_

Not sure if this helps. I engineered the request using `cURL`.

```
curl -v --http1.1 -X POST -H 'Content-Type: application/json' -d '{ "tag": "v0.32.0" }' -H 'Authorization:  <remove for security reasons>' "https://atom.io/api/packages/build/versions"
* Hostname was NOT found in DNS cache
*   Trying 107.21.209.157...
* Connected to atom.io (107.21.209.157) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
* Server certificate: *.atom.io
* Server certificate: DigiCert SHA2 High Assurance Server CA
* Server certificate: DigiCert High Assurance EV Root CA
> POST /api/packages/build/versions HTTP/1.1
> User-Agent: curl/7.37.1
> Host: atom.io
> Accept: */*
> Content-Type: application/json
> Authorization: <removed for security reasons>
> Content-Length: 20
>
* upload completely sent off: 20 out of 20 bytes
< HTTP/1.1 500 Internal Server Error
* Server Cowboy is not blacklisted
< Server: Cowboy
< Connection: close
< Date: Thu, 14 May 2015 08:40:31 GMT
< Status: 500 Internal Server Error
< Strict-Transport-Security: max-age=631152000
< X-Frame-Options: DENY
< X-Xss-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Content-Security-Policy: default-src 'self'; connect-src 'self'; font-src 'self'; frame-src 'self'; img-src https://* 'self' data:; media-src 'none'; object-src 'self'; script-src 'self' 'unsafe-inline' https://ssl.google-analytics.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline';
< Content-Type: application/json; charset=utf-8
< Cache-Control: no-cache
< Set-Cookie: request_method=POST; path=/; secure
< X-Request-Id: b87c974b-3129-4ff5-8376-6df676e00c53
< X-Runtime: 0.458679
< X-Rack-Cache: invalidate, pass
< Via: 1.1 vegur
<
* Closing connection 0
{"message":"Application error"}
```

If there's anything else I can do, let me know.

**Comment by thedaniel** [comment]
Thanks for the details - I haven't fixed this yet, but I want to give an update; I see the failed requests in the server logs, but not in our internal exception tracking system, which makes it a little more difficult to reproduce. I'll update this thread when I know more.

**Comment by thedaniel** [comment]
_From @noseglid on May 14, 2015 21:31_

It is happend **every** time I try to publish `v0.32.0` for the `build` package. You're welcome to publish it as a means to reproduce it. And if you succeed, it's all good!

**Comment by thedaniel** [comment]
@noseglid strangely enough, there was a version 0.32.0 in the DB pointing to [this commit](https://github.com/noseglid/atom-build/commit/fb265b35598ff429528996a394a15a299f938287) from 2 weeks ago, that was created the same day as that commit's date. After I deleted that row from the DB, I was able to re-import a new 0.32.0 from the v0.32.0 tag: https://atom.io/packages/build

I'm not sure how it happened, but basically a version 0.32.0 of build had already been published, and then other, earlier versions were created, and when you tried to publish another 0.32.0, the app crashed rather than giving you a reasonable error message.

@cs150bf I'll investigate your package tomorrow.

**Comment by thedaniel** [comment]
_From @noseglid on May 15, 2015 6:52_

@thedaniel Aha! I might be able to  give some insight on that.

I did `apm publish` (on `0.31.0`) without the proper proxy/socksify connections set, which pushed the tag to github but never succeeded in publishing the package (from what I gathered at least).

I fixed the proxy settings and did another publish which succeeded (but this time it accidentally became v0.32.0).

Realizing my mistake, I removed the tags, forced pushed master on github to remove the `Preparing v0.32.0`-commit and unpublished `0.32.0` and went on to publish `0.31.0`. Now it is 2 weeks later and voila.

That's the most accurate description I can give from memory. Maybe it is the `unpublish` command that doesn't really work?

**Comment by thedaniel** [comment]
_From @magalhas on May 20, 2015 23:1_

I'm having the same symptoms with the `jenkins` package for over a month. I've tried different machines, `apm` setup is fine.

**Comment by thedaniel** [comment]
_From @magalhas on June 6, 2015 17:43_

What's the status on this? Atom 1.0 is almost out and I can't release my updated package without deprecated APIs.

**Comment by thedaniel** [comment]
Sorry about this, I'll take a look at it.

**Comment by thedaniel** [comment]
_From @magalhas on June 9, 2015 8:31_

@thedaniel let me know

**Comment by thedaniel** [comment]
@magalhas i see the errors in our exception tracking system, but I also notice that the version (0.3.2) in package.json on master matches the latest version here: https://atom.io/packages/jenkins

Is it possible that the package published successfully even though there was an error?

**Comment by thedaniel** [comment]
@magalhas exactly what apm command are you running?

**Comment by thedaniel** [comment]
_From @magalhas on June 10, 2015 23:9_

`apm publish patch`. After getting the application error message I've also tried unpublishing but it says that the version is not found.

**Comment by thedaniel** [comment]
@magalhas I see an unpublished 0.3.3 in the db and some deleted tags in GitHub staff tools. The API won't let you unpublish a version and then publish the same one with a different tag - force pushing & deleting history in general leads to some unfortunate behavior in the atom.io API as it's closely tied to the GitHub repo. You can likely publish 0.3.4 though. I'm working on a fix for the API that does a better job of reporting the nature of the error rather than just crashing, and if apm makes it difficult for you to publish the right version for any reason, let me know and we can work on that (or you can make the calls directly via curl)

**Comment by thedaniel** [comment]
_From @magalhas on June 11, 2015 10:15_

@thedaniel I was able to publish v0.3.4 as you've stated, though not being able to publish v0.3.3 is still harsh to understand for me. Thank you for your feedback :+1:

**Comment by thedaniel** [comment]
_From @kmorey on June 18, 2015 16:22_

I'm having this issue with my package as well this morning. How can I resolve it?

**Comment by jacogr** [comment]
Same here. 3 packages, 2 were fine the 3rd gave the issue. Yes, I am logged-in, yes I re-logged-in, yes other packages work - before and after my trial and tribulations. I have tried multiple times and completely screwed up the tags now.

This is the one that doesn't publish 

https://atom.io/packages/git-control

Did it again, just to copy n paste.

```
➜  git-control git:(master) apm publish patch 
Preparing and tagging a new version ✓
Pushing v0.4.5 tag ✓
Publishing git-control@v0.4.5 ✗
Creating new version failed: Application error
```

**Comment by thedaniel** [comment]
I mentioned this in another issue, but you should be able to avoid triggering this bug by removing the `_atomPackageCache` key in package.json.

**Comment by ioquatix** [comment]
I'm having this problem with `script-runner`.

```
^_^ > apm publish minor
Preparing and tagging a new version ✓
Pushing v2.4.0 tag Username for 'https://github.com': ioquatix
Password for 'https://ioquatix@github.com': 
✓
Publishing script-runner@v2.4.0 ✗
Creating new version failed: Application error
```

I tried again:

```
^_^ > apm publish --tag v2.4.0
Publishing script-runner@v2.4.0 ✗
Creating new version failed: Application error
```

@thedaniel can you help?

**Comment by lee-dohm** [comment]
@ioquatix Have you tried `apm login`? Have you removed the `_atomPackageCache` key in `package.json`? Have you tried the other debugging steps mentioned above?

**Comment by ioquatix** [comment]
Yes login working fine and there was no such key.

**Comment by ioquatix** [comment]
This is still failing and I can't publish my package/update.

```
^_^ > apm login
Welcome to Atom!

Before you can publish packages, you'll need an API token.

Visit your account page on Atom.io https://atom.io/account,
copy the token and paste it below when prompted.

Press [Enter] to open your account page on Atom.io. 
Token> ***********************************
Saving token to Keychain ✓
^_^ > apm publish --tag v2.4.0
Publishing script-runner@v2.4.0 ✗
Creating new version failed: Application error
```

**Comment by ioquatix** [comment]
```
^_^ > cat package.json 
{
  "name": "script-runner",
  "main": "./lib/script-runner",
  "version": "2.4.0",
  "description": "Run scripts and shells within a proper terminal.",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/ioquatix/script-runner"
  },
  "bugs": {
    "url": "https://github.com/ioquatix/script-runner/issues"
  },
  "homepage": "https://github.com/ioquatix/script-runner",
  "dependencies": {
    "shellwords": "^0.1.0",
    "etch": "^0.12.0",
    "shell-environment": "^0.3.0",
    "xterm": "^3.3",
    "node-pty-prebuilt": "^0.7.0",
    "temp-write": "^3.4",
    "resize-observer-polyfill": "^1.4"
  }
}
```

**Comment by ioquatix** [comment]
@thedaniel @lee-dohm this is blocking my ability to publish package release, is there any chance we can work through this? Happy to give you any further information.

**Comment by ioquatix** [comment]
Link to package if it helps https://atom.io/packages/script-runner

**Comment by thedaniel** [comment]
i don't work on this project anymore, good luck

**Comment by thedaniel** [comment]
@lee-dohm do you mind unassigning this from me? i think it's a little confusing to people to see my face at the top as the assignee.

**Comment by ioquatix** [comment]
@jasonrudolph any chance to get some attention to this issue? It's blocking me from publishing updated packages. I followed all advice given but nothing worked.

**Comment by ioquatix** [comment]
@50Wliu sorry, just trying to pull someone in who can help or get some traction for this issue. This is a major blocking issue, I can't release any update to my package which currently has around 70k downloads. I really want to release an update!

**Comment by rsese** [comment]
Hi @ioquatix :wave: apologies for the delay! I just wanted to acknowledge that I've seen your messages.  Though I can't make any specific promises about a timeline for help, I'll bring this up with the other maintainers for you and we'll followup as soon as we can.

Please note however that though I totally understand that you'd love help releasing a package update, pinging multiple people individually across multiple comments isn't the best way to get attention on your issue (someone may be out, working on very specific prioritized work, etc.).  My suggestion in the future would be if you haven't heard back from us for a while is to open a new issue summarizing the problem, what you've tried, what you see, and what you expect.  Especially in a case like this where it's an older issue that you didn't open and it sounds like the [suggested fix](https://github.com/atom/atom.io/issues/7#issuecomment-174093381) didn't help, starting with a new issue would be super helpful.

**Comment by ioquatix** [comment]
Okay should I make a new issue now?

**Comment by rsese** [comment]
Sorry I should have been more clear about that, yes please do @ioquatix thank you :bow:

**Comment by ioquatix** [comment]
I think you should close this issue.
