### ISSUE TITLE
Is the newsletter active?

### ISSUE THREAD

**Issue by mightyiam** [atom/atom.io#74]
I didn't get a message about the release of 1.8.

**Comment by lee-dohm** [comment]
No, we never did manage to get the newsletter off the ground. You can be notified of releases (and other Atom news) by subscribing to the [Atom blog RSS feed](http://blog.atom.io/feed.xml) or there is also a [feed specifically for Atom releases](https://github.com/atom/atom/releases.atom).

I'm also working right now to remove the Keep In Touch Email link.

**Comment by lee-dohm** [comment]
Thanks for bringing it up!
