### ISSUE TITLE
Broken Link in Workspace documentation

### ISSUE THREAD

**Issue by zoo1** [atom/atom.io#80]
In the documentation for the Workspace Class, the open method contains a broken link. The broken link is the "Promise" in the return values block. 
![capture 2016-06-04 at 11 15 01](https://cloud.githubusercontent.com/assets/4008169/16493560/f2d6e116-3eb3-11e6-861e-17bfe98aa192.png)

**Comment by winstliu** [comment]
This issue was moved to atom/flight-manual.atom.io#236

**Comment by winstliu** [comment]
Whoops...moved it to the wrong repo D:.

**Comment by winstliu** [comment]
@zoo1 to prevent more issue/comment spam, can you please manually move this to the atom/atom repo?  Thanks, and sorry for all the trouble.
