### ISSUE TITLE
editor screenshot image repeats on landscape mode

### ISSUE THREAD

**Issue by bvanrijn** [atom/atom.io#81]
The editor screenshot on the Atom homepage repeats when I view the website in landscape mode on my iPhone 6. If there are any more details I need to provide, please let me know.

![image](https://cloud.githubusercontent.com/assets/11941174/16585975/ce5021cc-42c3-11e6-9d90-953b3b7ab116.png)

<strike>_(On a related, but side note: I've always wondered what theme is being used in that screenshot?)_</strike> It's just One Dark.

**Comment by bvanrijn** [comment]
The syntax themes I found that most closely resemble the one used in the screenshot are

- [tinacious-design-syntax] https://atom.io/themes/tinacious-design-syntax
- [oceans16-syntax](https://atom.io/packages/oceans16-syntax)

**Comment by winstliu** [comment]
@bvanrijn Off-topic, but I believe it's actually One Dark Vivid :).

**Comment by jasonrudolph** [comment]
This should be resolved now. If you continue to notice any weirdness, please let us know. :bow:

**Comment by bvanrijn** [comment]
Will do! Everything seems to be 👌 now.
