### ISSUE TITLE
git-integration post formatting error

### ISSUE THREAD

**Issue by pbiggar** [atom/atom.io#87]
Not sure this is the right place to report this, but this page (http://blog.atom.io/2014/03/13/git-integration.html) on the blog is formatted incorrectly. From `## Status bar icons` to the end are contained within a code block.

I wouldn't ordinarily mention it, but it seems to be the only docs on the web about the git integration, and I found it very useful.

**Comment by lee-dohm** [comment]
Thanks for the report. It should be fixed now :grinning:
