### ISSUE TITLE
Provide Information on GitHub Account Permissions

### ISSUE THREAD

**Issue by ashcrow** [atom/atom.io#96]
The following stopped me from authorizing the login:

```
Atom.io by atom would like permission to access your account ashcrow

Review permissions

Organizations and teams
Read-only access
```

I know atom.io is run by GitHub but it would be nice to have an explanation around why it requires access to public and private teams and organizations (even being read-only).

**Comment by ashcrow** [comment]
@lee-dohm can you provide some info? 😄

**Comment by lee-dohm** [comment]
We have the organizations and teams access in there so that the atom.io website can use it to determine if someone is on one of the Atom teams and can therefore admin the site.
